name: Lint Python and Format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install mypy diopter pytest
      - name: run mypy
        run: python -m mypy --strict 
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install black
      - name: Check formating with black
        run: python -m black --check python_src/
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install . flake8
      - name: run flake8
        run: python -m flake8 python_src
  isort:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        - run: python -m pip install isort
        - name: Check imports with isort
          run: python -m isort --profile black --check python_src
