on: [ push ]
name: Run C++ tests
jobs:
  catchpp:
    strategy:
      matrix:
        version: [14,15]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main'
          sudo apt remove clang-14 clang-13 clang-12 llvm-14 llvm-13 llvm-12
          sudo apt-get update
          sudo apt-get install ninja-build catch2 clang-${{ matrix.version }} libclang-${{ matrix.version }}-dev libclang-cpp${{ matrix.version }}-dev
      - name: Build and run tests
        run: |
          mkdir build
          cd build 
          cmake .. -GNinja -DBUILD_TESTING=ON 
          ninja
      - name: Run tests
        run: |
          cd build
          ctest
